on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create OSX Release

jobs:
  build:
    name: Build and Upload OSX Binaries
    runs-on: macos-latest
    permissions:
      contents: write
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup build environment
        run: |
          # Install required build tools for macOS
          brew install llvm
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Build release
        env:
          CC: clang
          CXX: clang++
        run: |
          cargo build --release --target=${{ matrix.target }}
      - name: Strip binary
        run: |
          strip target/${{ matrix.target }}/release/zinit
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/release/zinit
          name: Release ${{ github.ref_name }} - OSX
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
